name: Build and Deploy main

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run check
    - run: npm run test
    - name: Github Tag with semantic versioning
      id: versioning
      uses: hennejg/github-tag-action@v4.3.1
      with:
        release_branches: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: npm run build
      env:
        VERSION_NUMBER: ${{steps.versioning.outputs.new_version}}
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./public
